# Generated by Django 3.2 on 2021-04-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210426_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='number')),
                ('hardware', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
